name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh > install_cli.sh
        bash install_cli.sh
        echo "$PWD/bin" >> $GITHUB_PATH
        sudo apt-get update && sudo apt-get install -y zip python3-pip
        pip3 install markdown pyserial adafruit-nrfutil ecdsa --break-system-packages || pip3 install markdown pyserial adafruit-nrfutil ecdsa

    - name: Setup missing links in config
      run: |
        sed -i '/unsignedio:avr/d' Makefile
        sed -i '/unsigned.io/d' arduino-cli.yaml

    - name: Prepare build
      run: make prep

    - name: Setup missing Console dependencies
      run: |
        mkdir -p ../dist_archive/reticulum.network/gfx
        touch ../dist_archive/rns-1.0.3-py3-none-any.whl ../dist_archive/nomadnet-0.9.1-py3-none-any.whl ../dist_archive/lxmf-0.9.3-py3-none-any.whl ../dist_archive/rnsh-0.1.5-py3-none-any.whl
        sed -i 's/exit(1)/pass/' Console/build.py
        sed -i -E 's/(arduino-cli compile) --/\1 .\/ --/g' Makefile

    - name: Build firmware
      run: make release
